version: '3'

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    container_name: timescaledb
    environment:
      - POSTGRES_PASSWORD=asmadmin
      - POSTGRES_DB=dalang_watcher
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - timescale_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - asm_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  asm_api:
    build:
      context: .
      dockerfile: docker/api.dockerfile
    container_name: asm_api
    depends_on:
      - timescaledb
    environment:
      - DB_HOST=timescaledb
      - DB_PORT=5432
      - DB_NAME=dalang_watcher
      - DB_USER=postgres
      - DB_PASSWORD=asmadmin
      - CURRENT_USER=trinq
    ports:
      - "5000:5000"
    cap_add:
      - NET_RAW
      - NET_ADMIN
    networks:
      - asm_network
    restart: always

networks:
  asm_network:
    driver: bridge

volumes:
  timescale_data: